hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - dataset: cifar10
  - optimizer: adamw
  - _self_

seed: 1
use_ddp: true
patch_size: 4
dim: 512
warmup_epochs: 10
num_epochs: 1000
