hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - dataset: mnist
  - optimizer: sgd
  - _self_

seed: 42
dim: 512
noise_ratio: 0.1
pretrain_num_epochs: 300
num_epochs: 2000
save_model: false
pretrain_sample_size: 10000 # use 3000 for stl10 and pneumoniamnist, 200 for breastmnist
sample_size: 200
revert_weights: true

wandb:
  project: benign_attention
  entity: keitaroskmt
  job_type: vit_finetune
