hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - dataset: cifar10
  - optimizer: sgd
  - _self_

seed: 1
use_ddp: true
dim: 512
noise_ratio: 0.0
pretrain_num_epochs: 100
num_epochs: 400
save_model: false
pretrain_sample_size: 10000
sample_size: 5000
