hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_

delta: 0.01
n: 20
T: 8
rho: 0.2
embed_dim: 4000
learning_rate: 1e-4
signal_norm: 20.0
num_steps: 5000
noise_ratio: 0.2
num_test_samples: 1000
